[env]
AUTOGROWER_SSE_URL = "https://api.autogrower.eu"
AUTOGROWER_BACKEND_API = "https://api.autogrower.eu"

[alias]
cov = "tarpaulin --out html --all-targets"
ut = "test --tests"
d = "doc --open --no-deps"
lint = "clippy"
