name: CI

on: pull_request

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: packages/backend

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: |
          cargo build --verbose;

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Run tests
        run: |
          cargo test --tests --verbose

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Check formatting - rustfmt
        run: cargo fmt --all -- --check

      - name: Check good practice - clippy
        run: cargo clippy -- -Dwarnings
